on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Generate version number
        run: |
          npm --no-git-tag-version version $(cat package.json | sed -n '/"version": "*/ { s///; s/".*//; p; q; }')-${{github.run_number}}
      
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
